server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

logging:
  level:
    root: ${LOG_ROOT_LEVEL}
    com.alexey.tabgenerator: ${LOG_APP_LEVEL}
    org.springframework.web: ${LOG_WEB_LEVEL}

file:
  upload-dir: uploads/audio/tabs

client-host:
  adress: ${CLIENT_HOST}

ml:
  base-url: ${ML_BASE_URL}
  generate-endpoint: ${ML_GENERATE_ENDPOINT}
  timeout-seconds: 180

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}